services:
  postgres:
    image: postgres:16-alpine
    container_name: camera-monitoramento-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-camera_monitoramento}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Define POSTGRES_PASSWORD no arquivo .env}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
